#cloud-config

write_files:
- owner: root:root
  path: /etc/netplan/60-floating-ip.yaml
  content: |
    network:
      version: 2
      renderer: networkd
      ethernets:
        eth0:
          addresses:
          - ${floating_ip}/32

runcmd:
# Enable floating IP
- netplan apply
# Create administrative user without password
# We will set this later through ansible
- adduser user --disabled-password --gecos ""
- usermod -aG sudo user
# Copy root's authorized_keys so we can auth as 'user' through ssh
- mkdir /home/user/.ssh
- cp /root/.ssh/authorized_keys /home/user/.ssh/
- chown -R user:user /home/user/.ssh
- chmod -R 700 /home/user/.ssh
