---
- name: Harden SSH Daemon
  become: true
  register: sshd_config_file
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "{{ item.regexp | default(omit) }}"
    line: "{{ item.line }}"
    state: "{{ item.state | default('present') }}"
  with_items:
  - line: "Protocol 2"
  - line: "Protocol 1"
    state: "absent"
  - line: "RSAAuthentication yes"
    state: "absent"
  - regexp: "^PermitRootLogin\ "
    line: "PermitRootLogin no"
  - regexp: "^PasswordAuthentication\ "
    line: "PasswordAuthentication no"
  - regexp: "^PermitEmptyPasswords\ "
    line: "PermitEmptyPasswords no"
  - regexp: "^StrictModes\ "
    line: "StrictModes yes"
  - regexp: "^IgnoreRhosts\ "
    line: "IgnoreRhosts yes"
  - regexp: "^RhostsAuthentication\ "
    line: "RhostsAuthentication no"
  - regexp: "^RhostsRSAAuthentication\ "
    line: "RhostsRSAAuthentication no"
  - regexp: "^ClientAliveInterval\ "
    line: "ClientAliveInterval 300"
  - regexp: "^ClientAliveCountMax\ "
    line: "ClientAliveCountMax 0"
  - regexp: "^AllowTcpForwarding\ "
    line: "AllowTcpForwarding no"
  - regexp: "^X11Forwarding\ "
    line: "X11Forwarding no"
  - regexp: "^KexAlgorithms\ "
    line: "KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256"
  - regexp: "^Ciphers\ "
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr"
  - regexp: "^MACs\ "
    line: "MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com"

- name: Reload sshd
  become: yes
  service:
    name: sshd
    state: reloaded
  when: sshd_config_file.changed
